[project]
name = "card-analyzer-dcg"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "asgiref==3.12.1",
    "certifi==2026.7.22",
    "charset-normalizer==3.4.9",
    "dj-database-url==3.1.2",
    "django==6.0.7",
    "django-cors-headers==4.9.0",
    "djangorestframework==3.18.0",
    "gunicorn==26.0.0",
    "idna==3.18",
    "packaging==26.2",
    "psycopg-binary==3.3.4 ; implementation_name != 'pypy'",
    "psycopg[binary]==3.3.4",
    "requests==2.34.2",
    "sqlparse==0.6.0",
    "tzdata==2026.3 ; sys_platform == 'win32'",
    "urllib3==2.7.0",
]
