# Generated by Django 4.2.30 on 2026-08-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigimonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rarity', models.CharField(blank=True, default='', max_length=64)),
                ('card_type', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('card_level', models.CharField(blank=True, default='', max_length=32)),
                ('play_cost', models.CharField(blank=True, default='', max_length=32)),
                ('expansion', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subtype', models.TextField(blank=True, default='')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('variant_type', models.CharField(choices=[('standard', 'Standard Art'), ('alternate_art', 'Alternate Art (Parallel Rare)'), ('promo', 'Promo Variant'), ('errata', 'Text Correction / Errata')], default='standard', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('storage_backend', models.CharField(default='vercel_blob', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='analytics.digimoncard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cardimage',
            constraint=models.UniqueConstraint(fields=('card', 'source_filename'), name='unique_card_image_source'),
        ),
    ]
