# Generated by Django 4.2.30 on 2026-08-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigimonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rarity', models.CharField(blank=True, default='', max_length=64)),
                ('card_type', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('card_level', models.CharField(blank=True, default='', max_length=32)),
                ('play_cost', models.CharField(blank=True, default='', max_length=32)),
                ('expansion', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subtype', models.TextField(blank=True, default='')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
    ]
