# Generated by Django 4.2.30 on 2026-08-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_card_carddatasource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardDataSource',
        ),
    ]
