# Generated by Django 4.2.30 on 2026-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_delete_card_delete_carddatasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('expansion_code', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
        ),
    ]
