# Generated by Django 4.2.30 on 2026-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_cardexpansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardexpansion',
            name='expansion_code',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
